services:
  procpag:
    image: docker.io/erickemprobr/procpag:latest 
    ports: 
    - "8089:8089"
    networks:
    - fase3net
  
  # adicione os seus outros serviços aqui
  # faça com que todos os serviços usem a mesma rede 'fase3net'
  db:
    image: docker.io/erickemprobr/postgres:15
    container_name: hospital_tech
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:	
      - fase3net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9000:80"
    networks:
      - fase3net
networks:
  fase3net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
